import re

with open('index.html', 'r') as f:
    content = f.read()

new_tbody = '''<tbody id="catalog-body">
<tr><td>1</td><td><strong>BEBA</strong></td><td><span class="status-ok">✓ 100%</span></td><td><span class="status-warn">0% rec.</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>2</td><td><strong>BESAME</strong></td><td><span class="status-ok">✓ 75%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>3</td><td><strong>BUSCANDO</strong></td><td><span class="status-ok">✓ 99%</span></td><td><span class="status-ok">✓ 1%</span></td><td><span class="status-bad">✗</span></td><td><a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>4</td><td><strong>CODIGOS</strong> <span style="color:var(--text3);font-size:11px;">feat. Oveja Negra</span></td><td><span class="status-ok">✓ 90%</span></td><td><span class="status-ok">✓ 10%</span></td><td><span class="status-bad">✗</span></td><td><a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>5</td><td><strong>CONFIESO</strong></td><td><span class="status-ok">✓ 60%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>6</td><td><strong>CORITO SANO</strong> <span style="color:var(--text3);font-size:11px;">feat. Oveja Negra</span></td><td><span class="status-ok">✓ 49%</span></td><td><span class="status-ok">✓ 50%</span></td><td><span class="status-bad">✗</span></td><td><a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>7</td><td><strong>DESEOS</strong> <span style="color:var(--text3);font-size:11px;">feat. Toby Love</span></td><td><span class="status-ok">✓ 67%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>8</td><td><strong>DIOSA</strong></td><td><span class="status-ok">✓ 100%</span></td><td><span class="status-warn">0% rec.</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr style="background:rgba(239,68,68,0.04)"><td>9</td><td><strong>HOY SE VA BEBE</strong> <span style="background:rgba(59,130,246,0.15);color:#93c5fd;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">📺 Si Se Puede</span></td><td><span class="status-ok">✓ 90%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP ⚠</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>10</td><td><strong>LA PLATA</strong> <span style="color:var(--text3);font-size:11px;">feat. Jhon Blade</span></td><td><span class="status-ok">✓ 50%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr style="background:rgba(239,68,68,0.04)"><td>11</td><td><strong>LA QUE VALE</strong> <span style="background:rgba(59,130,246,0.15);color:#93c5fd;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">📺 Si Se Puede</span></td><td><span class="status-ok">✓ 60%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP ⚠</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>12</td><td><strong>MADRUGADA</strong></td><td><span class="status-ok">✓ 50%</span></td><td><span class="status-ok">✓ 25%</span></td><td><span class="status-bad">✗</span></td><td><a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>13</td><td><strong>MELODIA</strong></td><td><span class="status-ok">✓ 100%</span></td><td><span class="status-warn">0% rec.</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr style="background:rgba(239,68,68,0.08)"><td>14</td><td><strong>MOMENTOS</strong> <span style="color:var(--text3);font-size:11px;">feat. Oveja Negra, FaceVsIt</span> <span style="background:rgba(239,68,68,0.2);color:#fca5a5;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">NEW 2025</span></td><td><span class="status-bad">✗ NOT REG.</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://bmi.com/creators" target="_blank" class="pro-link">BMI</a> · <a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>15</td><td><strong>NO ME DIGAS QUE NO</strong> <span style="color:var(--text3);font-size:11px;">feat. Martes Jay</span></td><td><span class="status-ok">✓ 60%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>16</td><td><strong>NO TE TENGO</strong></td><td><span class="status-ok">✓ 100%</span></td><td><span class="status-warn">0% rec.</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>17</td><td><strong>NOCHE EN MIAMI</strong> <span style="color:var(--text3);font-size:11px;">feat. Kai Lani</span></td><td><span class="status-ok">✓ 100%</span></td><td><span class="status-warn">0% rec.</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>18</td><td><strong>OLVIDAR</strong> <span style="background:rgba(34,197,94,0.15);color:#86efac;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">📰 Billboard AR</span></td><td><span class="status-ok">✓ 99.5%</span></td><td><span class="status-ok">✓ 0.5%</span></td><td><span class="status-bad">✗</span></td><td><a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>19</td><td><strong>PLEASE</strong> <span style="color:var(--text3);font-size:11px;">feat. J Blxss</span></td><td><span class="status-ok">✓ 80%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr style="background:rgba(239,68,68,0.04)"><td>20</td><td><strong>TRAICION</strong> <span style="background:rgba(59,130,246,0.15);color:#93c5fd;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">📺 Si Se Puede</span></td><td><span class="status-ok">✓ 60%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP ⚠</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr style="background:rgba(239,68,68,0.04)"><td>21</td><td><strong>TU AMIGA</strong> <span style="background:rgba(59,130,246,0.15);color:#93c5fd;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">📺 Si Se Puede</span></td><td><span class="status-ok">✓ 60%</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP ⚠</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>22</td><td><strong>TU ESTILO</strong></td><td><span class="status-ok">✓ 100%</span></td><td><span class="status-warn">0% rec.</span></td><td><span class="status-bad">✗</span></td><td><a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr style="background:rgba(239,68,68,0.08)"><td>23</td><td><strong>UNA BANDIDA</strong> <span style="color:var(--text3);font-size:11px;">feat. Oveja Negra EC, Jordan</span> <span style="background:rgba(239,68,68,0.2);color:#fca5a5;font-size:10px;padding:2px 6px;border-radius:3px;font-family:var(--font-mono);">NEW 2025</span></td><td><span class="status-bad">✗ NOT REG.</span></td><td><span class="status-bad">✗</span></td><td><span class="status-bad">✗</span></td><td><a href="https://bmi.com/creators" target="_blank" class="pro-link">BMI</a> · <a href="https://aceonline.ascap.com" target="_blank" class="pro-link">ASCAP</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
<tr><td>24</td><td><strong>UNA NOCHE</strong> <span style="color:var(--text3);font-size:11px;">Debut 2012</span></td><td><span class="status-warn">⚠ Verify</span></td><td><span class="status-warn">⚠ Verify</span></td><td><span class="status-bad">✗</span></td><td><a href="https://bmi.com/creators" target="_blank" class="pro-link">Verify BMI</a> · <a href="https://sayce.com.ec" target="_blank" class="pro-link">SAYCE</a></td></tr>
</tbody>'''

content = re.sub(r'<tbody id="catalog-body">.*?</tbody>', new_tbody, content, flags=re.DOTALL)

# Update metrics
content = content.replace('>9</div>\n<div class="metric-sub">3 with registration gaps</div>', '>24</div>\n<div class="metric-sub">12 missing ASCAP · 2 unregistered</div>')
content = content.replace('Catalog — 9 Works', 'Catalog — 24 Works')

with open('index.html', 'w') as f:
    f.write(content)

print("Done")
